### ISSUE TITLE
"Status update failed: ... Cannot read property 'get' of undefined"

### ISSUE THREAD

**Issue by jzohrab** [covidatlas/li#135]
**Description**

When running tests, the following is shown on console.log:

```
  crawl saves files to cache

    ✓ Sandbox Found Architect project manifest, starting up
    Created test cache path/to/li/zz-testing-fake-cache
    ✔ No files in cache.
    Wrote to local cache: path/to/li/zz-testing-fake-cache/fake/2020-05-14/2020-05-14t17_29_05.366z-default-99fd8.json.gz
    Crawl fake: 1988.087ms
    ✔ have file after crawl.
    Deleted test cache path/to/li/zz-testing-fake-cache

  scrape extracts data from cached file

Status update failed: {
  "source": "fake",
  "event": "crawler",
  "status": "success"
}

    TypeError: Cannot read property 'get' of undefined
        at getLastStatus (path/to/li/src/events/status/get-last-status/index.js:4:36)
        at updateStatus (path/to/li/src/events/status/index.js:21:30)
...
```

The tests do not fail, so this is likely nothing (it's the initial status, after all)

**To Reproduce**

* Check out master (as at commit `54f340c329b499`)
* `npm run test`

**Comment by jzohrab** [comment]
I'll take a quick look, is probably nothing.

**Comment by jzohrab** [comment]
This problem appears to be intermittent -- possible timing issue.  Have done a few runs now and no error.

**Comment by jzohrab** [comment]
Yep, intermittent.  Happened now though, full console log of test:

```
MacBook-Air:li jeff$ npm run test:integration

> li@0.0.0 test:integration /Users/jeff/Documents/Projects/li
> tape 'tests/integration/**/*-test.js' | node tests/save-test-results.js | node tools/clean-tap-output.js | tap-spec; node tests/warnings.js


  crawl saves files to cache

    ✓ Sandbox Found Architect project manifest, starting up
    Created test cache /Users/jeff/Documents/Projects/li/zz-testing-fake-cache
    ✔ No files in cache.
    Wrote to local cache: /Users/jeff/Documents/Projects/li/zz-testing-fake-cache/fake/2020-05-14/2020-05-14t17_36_23.097z-default-99fd8.json.gz
    Crawl fake: 1088.852ms
    ✔ have file after crawl.
    Deleted test cache /Users/jeff/Documents/Projects/li/zz-testing-fake-cache

  scrape extracts data from cached file

Status update failed: {
  "source": "fake",
  "event": "crawler",
  "status": "success"
}

    TypeError: Cannot read property 'get' of undefined
        at getLastStatus (/Users/jeff/Documents/Projects/li/src/events/status/get-last-status/index.js:4:36)
        at updateStatus (/Users/jeff/Documents/Projects/li/src/events/status/index.js:21:30)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
        at async /Users/jeff/Documents/Projects/li/src/events/status/node_modules/@architect/functions/src/events/subscribe.js:28:18
        at async Promise.all (index 0)
        at async lambda (/Users/jeff/Documents/Projects/li/src/events/status/node_modules/@architect/functions/src/events/subscribe.js:25:14)
    Created test cache /Users/jeff/Documents/Projects/li/zz-testing-fake-cache
    Wrote to local cache: /Users/jeff/Documents/Projects/li/zz-testing-fake-cache/fake/2020-05-14/2020-05-14t17_36_26.407z-default-99fd8.json.gz
    Crawl fake: 831.889ms

```

**Comment by jzohrab** [comment]
The failing line in get-last-status is

```
getLastStatus (params, data) {
...
const result = await data.status.get({ source, event })
```

When this error is thrown,

```
params = {"source":"fake","event":"crawler","status":"success"}
data.status = undefined
```

If this method doesn't get called, the test exits with no weird console log.

Different fails happen at different times, just got

```
    TypeError: Cannot read property 'put' of undefined
        at logStatus (/Users/jeff/Documents/Projects/li/src/events/status/log/index.js:13:29)
```

**Comment by jzohrab** [comment]
This appears to be a timing problem where sandbox is shutdown before all async messages are processed.

in events/status/index.js, the code is:

```
    const data = await arc.tables()
...
    const lastStatus = await getLastStatus(params, data)
```

So `data` is null before it calls getLastStatus, and `arc.tables()` returns null.  Since this is only due to shutdown, we could perhaps just add a check for `data !== null` when doing the updates.

@ryanblock, thoughts?

**Comment by jzohrab** [comment]
Another similar error during testing.  Full stack:

```
  Live crawl and scrape

internal/modules/cjs/loader.js:985
  throw err;
  ^

Error: Cannot find module '@architect/shared/sources/_lib/constants.js'
Require stack:
- /Users/jeff/Documents/Projects/li/src/events/locations/get-location-names/index.js
- /Users/jeff/Documents/Projects/li/src/events/locations/index.js
- /Users/jeff/Documents/Projects/li/src/events/locations/[eval]
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Users/jeff/Documents/Projects/li/src/events/locations/get-location-names/index.js:5:24)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/jeff/Documents/Projects/li/src/events/locations/get-location-names/index.js',
    '/Users/jeff/Documents/Projects/li/src/events/locations/index.js',
    '/Users/jeff/Documents/Projects/li/src/events/locations/[eval]'
  ]
}

    Created test cache /Users/jeff/Documents/Projects/li/zz-testing-fake-cache
    ✔ using LI_CACHE_PATH
Status update failed: {
  "source": "fake",
  "event": "scraper",
  "status": "success"
}

    TypeError: Cannot read property 'put' of undefined
        at logStatus (/Users/jeff/Documents/Projects/li/src/events/status/log/index.js:13:29)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
        at async updateStatus (/Users/jeff/Documents/Projects/li/src/events/status/index.js:34:5)
        at async /Users/jeff/Documents/Projects/li/src/events/status/node_modules/@architect/functions/src/events/subscribe.js:28:18
        at async Promise.all (index 0)
        at async lambda (/Users/jeff/Documents/Projects/li/src/events/status/node_modules/@architect/functions/src/events/subscribe.js:25:14)
Some manner of strange error occurred: GotError: unable to verify the first certificate
    at onError (/Users/jeff/Documents/Projects/li/src/http/get-get-normal/node_modules/got/dist/source/request-as-event-emitter.js:140:29)
    at handleRequest (/Users/jeff/Documents/Projects/li/src/http/get-get-normal/node_modules/got/dist/source/request-as-event-emitter.js:173:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at TLSSocket.onConnectSecure (_tls_wrap.js:1473:34)
    at TLSSocket.emit (events.js:311:20)
    at TLSSocket.EventEmitter.emit (domain.js:482:12)
    at TLSSocket._finishInit (_tls_wrap.js:916:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:686:12) {
  name: 'RequestError',
  code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'
}
```

I had called `npx arc hydrate` very recently, so I don't understand why there'd be a 'missing module' error.

**Comment by jzohrab** [comment]
This is now handled by awaiting for some data in tests/integration/_lib/utils.
