### ISSUE TITLE
us-ga, us-wi reports 500 internal server error for headless browser, but source can be hit from chrome

### ISSUE THREAD

**Issue by jzohrab** [covidatlas/li#210]
**Description**

`Crawl returned status code: 500` for us-ga, but it looks like it should work.

**To Reproduce**

1. Checkout master
2. `$ ./start --crawl us-ga`
3. In server window, see error:

```
@event {
  "name": "status",
  "payload": {
    "source": "us-ga",
    "event": "crawler",
    "status": "failed"
  }
}
Crawler error { source: 'us-ga' }
Error: Crawl returned status code: 500
Type: headless (headless)
Params: {
  "type": "headless",
  "url": "https://ga-covid19.ondemand.sas.com/"
}
    at crawl (.../li/src/events/crawler/crawler/index.js:42:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async crawl (.../li/src/events/crawler/_crawl.js:37:24)
    at async crawlSource (.../li/src/events/crawler/index.js:9:5)
...(.../li/src/events/crawler/node_modules/@architect/functions/src/events/subscribe.js:25:14)
```

us-ga's crawl is:

```
      startDate: '2020-04-28',
      crawl: [
        {
          type: 'headless',
          url: 'https://ga-covid19.ondemand.sas.com/',
        },
      ],
```

That url works in regular chrome

**Comment by jzohrab** [comment]
Same issue for 'us-wi':

```
Crawler error { source: 'us-wi' }
Error: Crawl returned status code: 500
Type: headless (headless)
Params: {
  "type": "headless",
  "data": "table",
  "url": "https://www.dhs.wisconsin.gov/covid-19/county.htm"
}
    at crawl (/Users/jeff/Documents/Projects/li/src/events/crawler/crawler/index.js:42:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async crawl (/Users/jeff/Documents/Projects/li/src/events/crawler/_crawl.js:37:24)
    at async crawlSource (/Users/jeff/Documents/Projects/li/src/events/crawler/index.js:9:5)
    at async /Users/jeff/Documents/Projects/li/src/events/crawler/node_modules/@architect/functions/src/events/subscribe.js:28:18
    at async Promise.all (index 0)
    at async lambda (/Users/jeff/Documents/Projects/li/src/events/crawler/node_modules/@architect/functions/src/events/subscribe.js:25:14)
```

**Comment by jzohrab** [comment]
Found the issue, at least for staging, using https://api.staging.covidatlas.com/status?format=html:

```
Crawl returned status code: 500
Type: headless (headless)
Params: {
"type": "headless",
"timeout": 15000,
"data": "table",
"url": "https://www.health.gov.au/resources/total-covid-19-cases-and-deaths-by-states-and-territories"
}
Getter error: Error: Cannot find module 'puppeteer-core/lib/FrameManager'
Require stack:
- /var/task/node_modules/chrome-aws-lambda/source/puppeteer/lib/FrameManager.js
- /var/task/node_modules/chrome-aws-lambda/source/index.js
- /var/task/index.js
- /var/runtime/UserFunction.js
- /var/runtime/index.js
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
at Function.Module._load (internal/modules/cjs/loader.js:840:27)
at Module.require (internal/modules/cjs/loader.js:1019:19)
at require (internal/modules/cjs/helpers.js:77:18)
at Object. (/var/task/node_modules/chrome-aws-lambda/source/puppeteer/lib/FrameManager.js:6:11)
at Module._compile (internal/modules/cjs/loader.js:1133:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
at Module.load (internal/modules/cjs/loader.js:977:32)
at Function.Module._load (internal/modules/cjs/loader.js:877:14)
at Module.require (internal/modules/cjs/loader.js:1019:19)
```

**Comment by jzohrab** [comment]
We need to add `puppeteer-core` to `src/http/get-get-headless`, per the docs at https://www.npmjs.com/package/chrome-aws-lambda, adding now.

**Comment by jzohrab** [comment]
Added in https://github.com/covidatlas/li/pull/246, will merge and check.

**Comment by jzohrab** [comment]
Has been merged into master, waiting for deploy to staging and then will check to see if the errors go away.  Can check for `au`, currently fails for:

```
crawler: 
Crawl returned status code: 500
Type: headless (headless)
Params: {
  "type": "headless",
  "timeout": 15000,
  "data": "table",
  "url": "https://www.health.gov.au/resources/total-covid-19-cases-and-deaths-by-states-and-territories"
}
Getter error: Error: Cannot find module 'puppeteer-core/lib/FrameManager'
Require stack:
- /var/task/node_modules/chrome-aws-lambda/source/puppeteer/lib/FrameManager.js
- /var/task/node_modules/chrome-aws-lambda/source/index.js
- /var/task/index.js
- /var/runtime/UserFunction.js
- /var/runtime/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
    at Function.Module._load (internal/modules/cjs/loader.js:840:27)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object. (/var/task/node_modules/chrome-aws-lambda/source/puppeteer/lib/FrameManager.js:6:11)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
```

https://api.staging.covidatlas.com/status?format=html

**Comment by jzohrab** [comment]
Deployed successfully, hopefully all will be ok when it tries to run.  Will check again in a few hours.

**Comment by jzohrab** [comment]
It's still getting a 500 error ... not sure why!  The full error shown on the status page is now:

```
crawler: Crawl returned status code: 500Type: headless (headless)Params: {  "type": "headless",  "url": "https://ga-covid19.ondemand.sas.com/"}
```

so we're not getting the "missing module" ... hard to say what's up at the moment!  Trying this locally.

**Comment by jzohrab** [comment]
Local now shows:

```
Crawler error { source: 'us-ga' }
Error: Crawl returned status code: 500
Type: headless (headless)
Params: {
  "type": "headless",
  "url": "https://ga-covid19.ondemand.sas.com/"
}
    at crawl (/Users/jeff/Documents/Projects/li/src/events/crawler/crawler/index.js:42:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by jzohrab** [comment]
In `get-get-headless/index.js`, after the lines

```
    const response = await page.goto(url, {
      timeout: 30000,
      waitUntil: 'networkidle2'
    })
```

the status is 200, but the body is undefined, so the code is exiting.

**Comment by jzohrab** [comment]
Have merged in PR https://github.com/covidatlas/li/pull/247, tested locally and it works.  Will check https://api.staging.covidatlas.com/status?format=html in bit to see if that solves the problem. 

## Current items that have a 500 headless error are:

* au
* br
* us-ca-contra-costa-county
* us-ca-mono-county
* us-ca-san-benito-county
* us-ca-solano-county
* us-ga
* us-wi

```
crawler: 
Crawl returned status code: 500
Type: headless (headless)
Params: {
  "type": "headless",
  "timeout": 15000,
  "data": "table",
  "url": "https://www.health.gov.au/resources/total-covid-19-cases-and-deaths-by-states-and-territories"
}
```

## Others

us-nv-carson-city also has 500 err, but it's something else:

```
crawler: 
Crawl returned status code: 500
Type: headless (headless)
Params: {
  "type": "headless",
  "data": "table",
  "url": "https://gethealthycarsoncity.org/novel-coronavirus-2019/covid-19-by-county/",
  "options": {
    "disableSSL": true
  }
}
Getter error: Error: net::ERR_CERT_AUTHORITY_INVALID at https://gethealthycarsoncity.org/novel-coronavirus-2019/covid-19-by-county/
```

**Comment by jzohrab** [comment]
Nice, all of the 500-error crawls were fixed, per staging status https://api.staging.covidatlas.com/status?format=html.

```
au - fixed
br - fixed
us-ca-contra-costa-county - fixed
us-ca-mono-county - fixed
us-ca-san-benito-county - fixed
us-ca-solano-county - fixed
us-ga - fixed
us-wi - fixed
```
