### ISSUE TITLE
Sources cannot use ISO code for state

### ISSUE THREAD

**Issue by lazd** [covidatlas/li#23]
**Description**
[A clear and concise description of what the bug is.]

iso2 codes cause errors.

**To Reproduce**

```
const source = module.exports = {
  country: 'iso1:US',
  state: 'iso2:US-WA',
  ...
};
```

Results in error:
```
 AssertionError [ERR_ASSERTION]: State data not found for iso2:US-WA, undefined
    at calculateScraperTz (/Volumes/lazdRAID/Users/lazdHome/repos/li/src/events/scraper/find-tz/index.js:26:5)
    at scrapeSource (/Volumes/lazdRAID/Users/lazdHome/repos/li/src/events/scraper/index.js:30:22)
```

**Expected behavior**
[A clear and concise description of what you expected to happen.]

The above should work.

**Workaround**

Use 2 letter state code:

```
const source = module.exports = {
  country: 'iso1:US',
  state: 'WA',
  ...
};
```

**Comment by ryanblock** [comment]
Ah! Easy fix, stand by...
