### ISSUE TITLE
Behavior when startDate is undefined on scraper

### ISSUE THREAD

**Issue by lazd** [covidatlas/li#27]
## Description

Right now, we get an error:
```
❌ Failed to scrape us-vt: 
 Error: datetime.parse: Cannot parse undefined as date
    at parse (/Volumes/lazdRAID/Users/lazdHome/repos/li/src/events/scraper/node_modules/@architect/shared/datetime/_parse.js:14:33)
    at Object.dateIsBeforeOrEqualTo (/Volumes/lazdRAID/Users/lazdHome/repos/li/src/events/scraper/node_modules/@architect/shared/datetime/_compare.js:18:10)
    at findScraper (/Volumes/lazdRAID/Users/lazdHome/repos/li/src/events/scraper/find-scraper/index.js:16:20)
    at scrapeSource (/Volumes/lazdRAID/Users/lazdHome/repos/li/src/events/scraper/index.js:35:21)
    at async /Volumes/lazdRAID/Users/lazdHome/repos/li/src/events/scraper/node_modules/@architect/functions/src/events/subscribe.js:28:18
    at async Promise.all (index 0)
    at async lambda (/Volumes/lazdRAID/Users/lazdHome/repos/li/src/events/scraper/node_modules/@architect/functions/src/events/subscribe.js:25:14)
```

This isn't very helpful. Either the error should come from scraper validation, OR it should make an assumption.

Thoughts?

**Comment by jzohrab** [comment]
Meaning that the scraper doesn't have `startDate` ?  The unit test _should_ have caught that, in `unit/shared/sources/source-validation-test.js`.  We _could_ change this test so that it actually validates the source at runtime, but I don't know if that's helpful.  I'll add some tests now around this.

**Comment by jzohrab** [comment]
Current validation code isn't sufficient, I'm working on a fix in a branch.  Thanks Larry.

**Comment by jzohrab** [comment]
Double-checked this with a test in PR #55 ... but master should have already failed that scraper on validation (unit test) with this line: `assert.ok(is.string(startDate), 'Scraper must contain a startDate')`.  Not sure why that wasn't caught with this.

**Comment by ryanblock** [comment]
Same, is this still valid? If so, please reopen!
