### ISSUE TITLE
`TypeError` during internal API call to update locations

### ISSUE THREAD

**Issue by jzohrab** [covidatlas/li#81]
On master (as at `d89e3ad9e75b64`), run `$ TEST_ONLY=kr npm run test:integration`

The console log will show:

```
Status update: kr / scraper / success: 97.888ms
Failed to update locations iso1:kr#iso2:kr-11,iso1:kr#iso2:kr-26,iso1:kr#iso2:kr-27,iso1:kr#iso2:kr-28,iso1:kr#iso2:kr-29,iso1:kr#iso2:kr-30,iso1:kr#iso2:kr-31,iso1:kr#iso2:kr-50,iso1:kr#iso2:kr-41,iso1:kr#iso2:kr-42,iso1:kr#iso2:kr-43,iso1:kr#iso2:kr-44,iso1:kr#iso2:kr-45,iso1:kr#iso2:kr-46,iso1:kr#iso2:kr-47,iso1:kr#iso2:kr-48,iso1:kr#iso2:kr-49,iso1:kr#(unassigned),iso1:kr
    TypeError: Cannot read property 'toUpperCase' of undefined
        at /Users/jeff/Documents/Projects/li/src/events/locations/get-location-names/index.js:19:23
        at Array.map (<anonymous>)
        at getLocationNames (/Users/jeff/Documents/Projects/li/src/events/locations/get-location-names/index.js:7:37)
        at updateLocations (/Users/jeff/Documents/Projects/li/src/events/locations/index.js:15:27)
        at /Users/jeff/Documents/Projects/li/src/events/locations/node_modules/@architect/functions/src/events/subscribe.js:28:24
        at Array.map (<anonymous>)
        at lambda (/Users/jeff/Documents/Projects/li/src/events/locations/node_modules/@architect/functions/src/events/subscribe.js:25:46)
        at Socket.<anonymous> ([eval]:1:1155)
        at Socket.emit (events.js:311:20)
        at Socket.EventEmitter.emit (domain.js:482:12)
```

**Comment by ryanblock** [comment]
Wasn't guarding against `(unassigned)` entries during annotation. Am now! Pls take a look with the test suite?

**Comment by jzohrab** [comment]
It's still occurring on master as at `56c8729902cfc769`:

`TEST_ONLY=kr npm run test:integration`

```
    Local cache hit for: kr / 2020-05-06
Failed to update locations iso1:kr#iso2:kr-11,iso1:kr#iso2:kr-26,iso1:kr#iso2:kr-27,iso1:kr#iso2:kr-28,iso1:kr#iso2:kr-29,iso1:kr#iso2:kr-30,iso1:kr#iso2:kr-31,iso1:kr#iso2:kr-50,iso1:kr#iso2:kr-41,iso1:kr#iso2:kr-42,iso1:kr#iso2:kr-43,iso1:kr#iso2:kr-44,iso1:kr#iso2:kr-45,iso1:kr#iso2:kr-46,iso1:kr#iso2:kr-47,iso1:kr#iso2:kr-48,iso1:kr#iso2:kr-49,iso1:kr#(unassigned),iso1:kr

    TypeError: Cannot read property 'toUpperCase' of undefined
        at /Users/jeff/Documents/Projects/li/src/events/locations/get-location-names/index.js:19:23
        at Array.map (<anonymous>)
        at getLocationNames (/Users/jeff/Documents/Projects/li/src/events/locations/get-location-names/index.js:7:37)
        at updateLocations (/Users/jeff/Documents/Projects/li/src/events/locations/index.js:15:27)
        at /Users/jeff/Documents/Projects/li/src/events/locations/node_modules/@architect/functions/src/events/subscribe.js:28:24
        at Array.map (<anonymous>)
        at lambda (/Users/jeff/Documents/Projects/li/src/events/locations/node_modules/@architect/functions/src/events/subscribe.js:25:46)
        at Socket.<anonymous> ([eval]:1:1155)
        at Socket.emit (events.js:311:20)
        at Socket.EventEmitter.emit (domain.js:482:12)
    Status update: kr / scraper / success: 741.570ms
```

Note this happens during "historical scrape", when there is data in the crawler cache:

```
$ ls crawler-cache/kr
2020-05-02	2020-05-05	2020-05-06	2020-05-07
```

I'll take a look. :-)

**Comment by jzohrab** [comment]
Oh, I didn't see fix-81 branch!  Will try that now.

**Comment by jzohrab** [comment]
fix-81 fixes 81.

```
 Historical scrape

    ✔ using real cache
    Local cache hit for: kr / 2020-05-02
...
    ✔ kr cache scrape 2020-05-06 succeeded (1 record)
    Local cache hit for: kr / 2020-05-07
    Creating new location: seoul-kr / iso1:kr#iso2:kr-11
...
    Creating new location: unassigned-kr / iso1:kr#iso2:(unassigned)   <<<<
    Creating new location: kr / iso1:kr
    Update locations: 2083.106ms
    Status update: kr / scraper / success: 389.758ms
    Scrape: kr / 2020-05-07: 1132.370ms
    ✔ kr cache scrape 2020-05-07 succeeded (1 record)
    ✔ ok
```

**Comment by jzohrab** [comment]
Fixed in https://github.com/covidatlas/li/compare/fix-81, waiting for PR to be opened when you're good with it, @ryanblock .

**Comment by ryanblock** [comment]
Sorry, I got to it pretty late last night, thought I opened the PR for the branch (lol). Will merge as soon as tests pass!
